server:
  port: 9002

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/ms-test
    password: mysqldb
  zipkin:
    base-url: http://127.0.0.1:9411/
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: create-drop